<?php

namespace Database\Seeders;

use App\Models\SalesCourseBoardEntry;
use Illuminate\Database\Seeder;

class SalesCourseBoardSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            [
                'name' => 'AI Tools',
                'slug' => 'ai-tools',
                'audience' => 'Everyone',
                'instructor_name' => 'Shareif Abdelmoniem',
                'start_label' => 'Start of September',
                'schedule_days' => 'Saturday',
                'duration' => 'شهر ونصف',
                'hours' => '20',
                'price_online' => 3000,
                'price_recorded' => 1200,
                'format' => 'Recorded online',
                'summary' => 'كورس أدوات الذكاء الاصطناعي للجميع — نسخة أونلاين أو مسجّلة بأسعار مختلفة.',
                'landing_details' => "تعلّم أهم أدوات الذكاء الاصطناعي العملية للاستخدام اليومي والعمل.\n\n• مدرب: Shareif Abdelmoniem\n• البداية: Start of September\n• أيام المحاضرات: Saturday\n• المدة: شهر ونصف — 20 ساعة\n• أونلاين: 3000 ج.م | مسجّل: 1200 ج.م",
                'highlights' => [
                    'مناسب للجميع — بدون خلفية تقنية معقدة',
                    '20 ساعة تدريب مركز',
                    'خيار أونلاين أو مسجّل',
                ],
                'sort_order' => 1,
                'landing_published' => true,
            ],
            [
                'name' => 'Frontend',
                'slug' => 'frontend',
                'audience' => 'Students',
                'instructor_name' => 'Fatma Akram',
                'start_label' => 'Start of September',
                'schedule_days' => 'اثنين وخميس',
                'duration' => '4 شهور',
                'hours' => '100-150',
                'price_online' => 6000,
                'price_recorded' => null,
                'format' => 'Online / Recorded',
                'summary' => 'مسار Frontend شامل للطلاب — أونلاين أو مسجّل.',
                'landing_details' => "مسار Frontend من الصفر حتى بناء مشاريع حقيقية.\n\n• مدربة: Fatma Akram\n• البداية: Start of September\n• أيام المحاضرات: اثنين وخميس\n• المدة: 4 شهور — 100 إلى 150 ساعة\n• السعر: 6000 ج.م",
                'sort_order' => 2,
                'landing_published' => true,
            ],
            [
                'name' => 'Cyber Security',
                'slug' => 'cyber-security',
                'audience' => 'Students',
                'instructor_name' => 'Mohab Gaber',
                'start_label' => 'Start of September',
                'schedule_days' => 'حد وخميس',
                'duration' => '3 شهور',
                'hours' => '90-100',
                'price_online' => 8000,
                'price_recorded' => null,
                'format' => 'Online',
                'summary' => 'كورس Cyber Security أونلاين للطلاب.',
                'landing_details' => "مسار أمن سيبراني عملي يغطّي الأساسيات والتطبيق.\n\n• مدرب: Mohab Gaber\n• البداية: Start of September\n• أيام المحاضرات: حد وخميس\n• المدة: 3 شهور — 90 إلى 100 ساعة\n• السعر: 8000 ج.م — Online",
                'sort_order' => 3,
                'landing_published' => true,
            ],
            [
                'name' => 'Data Analysis',
                'slug' => 'data-analysis',
                'audience' => 'Students / Employees',
                'instructor_name' => 'Mohamed Elsaeed',
                'start_label' => '1/10',
                'schedule_days' => 'حد واربع',
                'duration' => '4.5 شهور',
                'hours' => '80',
                'price_online' => 7000,
                'price_recorded' => null,
                'format' => 'Online / Onsite / Recorded',
                'summary' => 'تحليل بيانات للطلاب والموظفين — أونلاين أو حضور أو مسجّل.',
                'landing_details' => "كورس Data Analysis يركّز على التحليل العملي واتخاذ القرار بالبيانات.\n\n• مدرب: Mohamed Elsaeed\n• البداية: 1/10\n• أيام المحاضرات: حد واربع\n• المدة: 4.5 شهور — 80 ساعة\n• السعر: 7000 ج.م",
                'sort_order' => 4,
                'landing_published' => true,
            ],
            [
                'name' => 'Data Science',
                'slug' => 'data-science',
                'audience' => 'Students',
                'instructor_name' => 'Ahmed Hafez',
                'start_label' => '1/10',
                'schedule_days' => 'سبت وتلات',
                'duration' => '9 شهور',
                'hours' => '150',
                'price_online' => 6500,
                'price_recorded' => null,
                'format' => 'Online',
                'summary' => 'مسار Data Science مكثّف للطلاب — 9 شهور أونلاين.',
                'landing_details' => "مسار Data Science شامل من الأساسيات إلى التطبيق.\n\n• مدرب: Ahmed Hafez\n• البداية: 1/10\n• أيام المحاضرات: سبت وتلات\n• المدة: 9 شهور — 150 ساعة\n• السعر: 6500 ج.م — Online",
                'sort_order' => 5,
                'landing_published' => true,
            ],
            [
                'name' => 'AI Automation',
                'slug' => 'ai-automation',
                'audience' => 'Students / Employees',
                'instructor_name' => 'Ahmed Madeh',
                'start_label' => '—',
                'schedule_days' => '—',
                'duration' => '—',
                'hours' => '30',
                'price_online' => 3000,
                'price_recorded' => null,
                'format' => 'Recorded',
                'summary' => 'أتمتة بالذكاء الاصطناعي — نسخة مسجّلة 30 ساعة.',
                'landing_details' => "كورس AI Automation مسجّل — 30 ساعة.\n\n• مدرب: Ahmed Madeh\n• السعر: 3000 ج.م\n• النظام: Recorded",
                'sort_order' => 6,
                'landing_published' => true,
            ],
            [
                'name' => 'UI/UX',
                'slug' => 'ui-ux',
                'audience' => 'Students / Career shift',
                'instructor_name' => 'Hassan Qassem',
                'start_label' => '—',
                'schedule_days' => '—',
                'duration' => '—',
                'hours' => '—',
                'price_online' => null,
                'price_recorded' => null,
                'format' => 'Needs details',
                'summary' => 'كورس UI/UX — التفاصيل قيد التحديث من الإدارة.',
                'landing_details' => null,
                'sort_order' => 7,
                'landing_published' => false,
            ],
            [
                'name' => 'Backend',
                'slug' => 'backend',
                'audience' => 'Students',
                'instructor_name' => null,
                'start_label' => '—',
                'schedule_days' => '—',
                'duration' => '—',
                'hours' => '—',
                'price_online' => null,
                'price_recorded' => null,
                'format' => 'Needs details',
                'summary' => 'كورس Backend — التفاصيل قيد الإعداد.',
                'landing_details' => null,
                'sort_order' => 8,
                'landing_published' => false,
            ],
        ];

        foreach ($courses as $row) {
            SalesCourseBoardEntry::query()->updateOrCreate(
                ['slug' => $row['slug']],
                array_merge($row, ['is_active' => true])
            );
        }
    }
}
